apiVersion: v1
kind: Service
metadata:
  name: age-calculator-service
spec:
  selector:
    app: age-calculator
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080
  type: LoadBalancer